package com.randeng.api.controller.common;

public enum ErrorCode {
    SUCCESS,
    VERIFICATION_CODE_EXCEEDS_LIMIT,
    REGISTER_MOBILE_USED,
    REGISTER_MOBILE_NOT_PROVIDED,
    REGISTER_NAME_NOT_PROVIDED,
    REGISTER_PASSWORD_NOT_PROVIDED,
    REGISTER_VERIFICATION_CODE_NOT_PROVIDED,
    REGISTER_VERIFICATION_CODE_EXPIRED,
    PASSWORD_RECOVER_USER_NOT_FOUND,
    PASSWORD_RECOVER_MOBILE_NOT_PROVIDED,
    PASSWORD_RECOVER_PASSWORD_NOT_PROVIDED,
    PASSWORD_RECOVER_VERIFICATION_CODE_NOT_PROVIDED,
    PASSWORD_RECOVER_VERIFICATION_CODE_EXPIRED,
    UNKNOWN,
    INVALID_HOSPITAL,
    INVALID_PURCHASE, INVALID_FUNDRAISING
}
